// Todas as strings do jogo. Uma versão PT-BR seria um segundo objeto com as mesmas chaves.
export const t = {
  stage: 'Stage',
  advance: 'Advance',
  gold: 'Gold',
  souls: 'Souls',
  prestige: 'Prestige',
  hero: 'Hero',
  enemy: 'Enemy',
  boss: 'Boss',
  dps: 'DPS',
  goldPerSecond: 'Gold/s',
  bossFled: (stage: number) => `Too slow. Back to Stage ${stage}.`,
  zones: { ruins: 'Ruins', catacombs: 'Catacombs', ravine: 'Ravine' },

  combat: 'Combat',
  upgrades: 'Upgrades',
  level: 'Lv',
  buy: 'Buy',
  max: 'MAX',
  upgradeNames: {
    attack: 'Attack',
    speed: 'Speed',
    critChance: 'Crit Chance',
    critDamage: 'Crit Damage',
    greed: 'Greed',
  },
  upgradeEffects: {
    attack: 'Damage',
    speed: 'Attacks',
    critChance: 'Crit chance',
    critDamage: 'Crit damage',
    greed: 'Gold',
  },
} as const;
